#!/usr/bin/bash

TEMP_FILE=$(mktemp)

if [ -p /dev/stdin ]; then
    stdinput=`cat`
else
    stdinput=""
fi

params="${@}"

sed -e $'s/;/\\\n/g'<<< "$stdinput; $params" | as -o $TEMP_FILE.o

ld --entry=0x0 -Ttext 200000 --oformat binary -o $TEMP_FILE.bin $TEMP_FILE.o && \
rm $TEMP_FILE.o

objdump -D -b binary -mi386:x86-64 $TEMP_FILE.bin && \
rm $TEMP_FILE.bin

