#!/usr/bin/bash

TEMP_FILE=$(mktemp)
assembler="as"

if [[ $1 == "--intel" ]] ; then
    assembler="nasm"
    shift
fi

if [[ $# -eq 0 ]] ; then
    stdinput=$(cat)
else
    stdinput="${@}"
fi

input=$(tr ';' '\n' <<< "$stdinput");

if [[ $assembler == "as" ]] ; then
    echo ".text" > "$TEMP_FILE.asm"
    echo "$input" >> "$TEMP_FILE.asm"
    as -o "$TEMP_FILE.o" "$TEMP_FILE.asm" && rm "$TEMP_FILE.asm"
else
    echo ".text:" > "$TEMP_FILE.asm"
    echo "$input" >> "$TEMP_FILE.asm"
    nasm -f elf64 -o "$TEMP_FILE.o" "$TEMP_FILE.asm" && rm "$TEMP_FILE.asm"
fi


objdump -D -mi386:x86-64 -j .text --visualize-jumps "$TEMP_FILE.o" && rm "$TEMP_FILE.o"

